---
deployment:
  tasks:
    - export DEPLOYPATH=/home/pixeowxb/noufilsaqib.com/test
    - cd /home/pixeowxb/repositories/Portfolio
    - pnpm install
    - pnpm build
    - /bin/cp -R artifacts/portfolio/dist/public/* $DEPLOYPATH/
